### ISSUE TITLE
Sporadic NullPointerException on ``/app/projects`` endpoint

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1267]
```
java.lang.NullPointerException: Cannot get property 'value' on null object

	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60) ~[groovy-3.0.7.jar!/:3.0.7]

	at org.codehaus.groovy.vmplugin.v8.IndyInterface.selectMethod(IndyInterface.java:346) ~[groovy-3.0.7.jar!/:3.0.7]

	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318) ~[groovy-3.0.7.jar!/:3.0.7]

	at skills.services.ProjectSortingService$_getUserProjectsOrder_closure2.doCall(ProjectSortingService.groovy:93) ~[classes!/:1.9.0-SNAPSHOT]
``

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1277
