### ISSUE TITLE
sporadic error when approving self report requests

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#1728]
Most likely related to the new `Project.description` field added in the last release

![image](https://user-images.githubusercontent.com/47030042/196950599-a09c9441-43bf-4cbc-8adc-32b75207442b.png)

```
2022-10-20 11:14:03.542 ERROR 9 --- [io-8443-exec-87] s.c.exceptions.RestExceptionHandler      : POST uri=/admin/projects/movies/approvals/approve, Unexpected Error

org.springframework.orm.jpa.JpaSystemException: Unable to access lob stream; nested exception is org.hibernate.HibernateException: Unable to access lob stream
    at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:331) ~[spring-orm-5.3.23.jar!/:5.3.23]
    at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:233) ~[spring-orm-5.3.23.jar!/:5.3.23]
    at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:551) ~[spring-orm-5.3.23.jar!/:5.3.23]
    at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61) ~[spring-tx-5.3.23.jar!/:5.3.23]
    at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242) ~[spring-tx-5.3.23.jar!/:5.3.23]
    at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152) ~[spring-tx-5.3.23.jar!/:5.3.23]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.23.jar!/:5.3.23]
    at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:145) ~[spring-data-jpa-2.6.7.jar!/:2.6.7]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.23.jar!/:5.3.23]
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.23.jar!/:5.3.23]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.23.jar!/:5.3.23]
    at org.springframework.data.repository.core.support.MethodInvocationValidator.invoke(MethodInvocationValidator.java:99) ~[spring-data-commons-2.6.7.jar!/:2.6.7]
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.23.jar!/:5.3.23]
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[spring-aop-5.3.23.jar!/:5.3.23]
    at jdk.proxy2/jdk.proxy2.$Proxy185.findByProjectId(Unknown Source) ~[na:na]
    at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318) ~[groovy-3.0.7.jar!/:3.0.7]
    at skills.services.SkillApprovalService.sentNotifications(SkillApprovalService.groovy:246) ~[classes!/:2.2.0-SNAPSHOT]
    at skills.services.SkillApprovalService.sentNotifications(SkillApprovalService.groovy) ~[classes!/:2.2.0-SNAPSHOT]
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
    at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[na:na]
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[groovy-3.0.7.jar!/:3.0.7]
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-3.0.7.jar!/:3.0.7]
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351) ~[groovy-3.0.7.jar!/:3.0.7]
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) ~[groovy-3.0.7.jar!/:3.0.7]
    at org.codehaus.groovy.vmplugin.v8.IndyInterface.selectMethod(IndyInterface.java:346) ~[groovy-3.0.7.jar!/:3.0.7]
    at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318) ~[groovy-3.0.7.jar!/:3.0.7]
    at skills.services.SkillApprovalService$_approve_closure7.doCall(SkillApprovalService.groovy:163) ~[classes!/:2.2.0-SNAPSHOT]
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
    at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[na:na]
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[groovy-3.0.7.jar!/:3.0.7]
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-3.0.7.jar!/:3.0.7]
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-3.0.7.jar!/:3.0.7]
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) ~[groovy-3.0.7.jar!/:3.0.7]
    at groovy.lang.Closure.call(Closure.java:412) ~[groovy-3.0.7.jar!/:3.0.7]
    at groovy.lang.Closure.call(Closure.java:428) ~[groovy-3.0.7.jar!/:3.0.7]
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2318) ~[groovy-3.0.7.jar!/:3.0.7]
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2303) ~[groovy-3.0.7.jar!/:3.0.7]
    at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2344) ~[groovy-3.0.7.jar!/:3.0.7]
    at org.codehaus.groovy.runtime.dgm$200.doMethodInvoke(Unknown Source) ~[groovy-3.0.7.jar!/:3.0.7]
    at org.codehaus.groovy.vmplugin.v8.IndyInterface.selectMethod(IndyInterface.java:346) ~[groovy-3.0.7.jar!/:3.0.7]
    at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318) ~[groovy-3.0.7.jar!/:3.0.7]
    at skills.services.SkillApprovalService.approve(SkillApprovalService.groovy:144) ~[classes!/:2.2.0-SNAPSHOT]
    at org.codehaus.groovy.vmplugin.v8.IndyInterface.selectMethod(IndyInterface.java:346) ~[groovy-3.0.7.jar!/:3.0.7]
    at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318) ~[groovy-3.0.7.jar!/:3.0.7]
    at skills.controller.SkillApprovalController.approve(SkillApprovalController.groovy:98) ~[classes!/:2.2.0-SNAPSHOT]
    at skills.controller.SkillApprovalController$$FastClassBySpringCGLIB$$3043332a.invoke(<generated>) ~[classes!/:2.2.0-SNAPSHOT]
```

**Comment by sudo-may** [comment]
:+1:
