### ISSUE TITLE
``ReportSkills_SelfReportApprovalWorkloadSpecs.user tags are configured to match multiple approvers - match starts with`` failed on CI

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1824]
```
[INFO] Running ReportSkills_SelfReportApprovalWorkloadSpecs
Error:  Tests run: 30, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 284.396 s <<< FAILURE! - in ReportSkills_SelfReportApprovalWorkloadSpecs
Error:  user tags are configured to match multiple approvers - match starts with  Time elapsed: 1.875 s  <<< ERROR!
java.lang.RuntimeException: error initializing UserAttrs for [usera]
	at skills.intTests.approverRole.ReportSkills_SelfReportApprovalWorkloadSpecs.createAdditionalApprovers(ReportSkills_SelfReportApprovalWorkloadSpecs.groovy:918)
	at skills.intTests.approverRole.ReportSkills_SelfReportApprovalWorkloadSpecs.user tags are configured to match multiple approvers - match starts with(ReportSkills_SelfReportApprovalWorkloadSpecs.groovy:479)
Caused by: org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [index_users_attrs_user_id]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
	at skills.intTests.approverRole.ReportSkills_SelfReportApprovalWorkloadSpecs.createAdditionalApprovers(ReportSkills_SelfReportApprovalWorkloadSpecs.groovy:918)
	at skills.intTests.approverRole.ReportSkills_SelfReportApprovalWorkloadSpecs.user tags are configured to match multiple approvers - match starts with(ReportSkills_SelfReportApprovalWorkloadSpecs.groovy:479)
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at skills.intTests.approverRole.ReportSkills_SelfReportApprovalWorkloadSpecs.createAdditionalApprovers(ReportSkills_SelfReportApprovalWorkloadSpecs.groovy:918)
	at skills.intTests.approverRole.ReportSkills_SelfReportApprovalWorkloadSpecs.user tags are configured to match multiple approvers - match starts with(ReportSkills_SelfReportApprovalWorkloadSpecs.groovy:479)
Caused by: org.postgresql.util.PSQLException: 
ERROR: duplicate key value violates unique constraint "index_users_attrs_user_id"
  Detail: Key (user_id)=(usera) already exists.
	at skills.intTests.approverRole.ReportSkills_SelfReportApprovalWorkloadSpecs.createAdditionalApprovers(ReportSkills_SelfReportApprovalWorkloadSpecs.groovy:918)
	at skills.intTests.approverRole.ReportSkills_SelfReportApprovalWorkloadSpecs.user tags are configured to match multiple approvers - match starts with(ReportSkills_SelfReportApprovalWorkloadSpecs.groovy:479)
```

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1826
