### ISSUE TITLE
Removing a skill from exporting fails if it was imported under a group in an another project

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#1889]
- export skill in project 1
- import skill under a group in project 2
- attempt to remove skill from exporting project 1

the following error occurs:
```
2022-12-08 16:57:21.239 ERROR 9 --- [nio-8443-exec-7] s.c.exceptions.RestExceptionHandler      : DELETE uri=/admin/projects/shows/skills/TheChase/export, Unexpected Error

java.lang.NullPointerException: Cannot get property 'type' on null object
	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60) ~[groovy-3.0.7.jar!/:3.0.7]
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.selectMethod(IndyInterface.java:346) ~[groovy-3.0.7.jar!/:3.0.7]
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318) ~[groovy-3.0.7.jar!/:3.0.7]
	at skills.services.UserAchievementsAndPointsManagement.handleSkillRemoval(UserAchievementsAndPointsManagement.groovy:63) ~[classes!/:2.3.0-SNAPSHOT]
	at skills.services.UserAchievementsAndPointsManagement$$FastClassBySpringCGLIB$$df3bc2ea.invoke(<generated>) ~[classes!/:2.3.0-SNAPSHOT]
```

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/1892

**Comment by dwalizer** [comment]
:+1:
