### ISSUE TITLE
Sporadic NPE during CI testing

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#2010]
```
java.lang.NullPointerException: Cannot invoke method convertToSkillsAuth() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:95) ~[groovy-4.0.7.jar!/:4.0.7]
	at org.codehaus.groovy.vmplugin.v8.IndyGuardsFiltersAndSignatures.invokeGroovyObjectInvoker(IndyGuardsFiltersAndSignatures.java:149) ~[groovy-4.0.7.jar!/:4.0.7]
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321) ~[groovy-4.0.7.jar!/:4.0.7]
	at skills.auth.form.oauth2.ResourceServerConfig$SkillsJwtAuthenticationConverter.convert(ResourceServerConfig.groovy:105) ~[classes!/:2.4.0-SNAPSHOT]
	at skills.auth.form.oauth2.ResourceServerConfig$SkillsJwtAuthenticationConverter.convert(ResourceServerConfig.groovy) ~[classes!/:2.4.0-SNAPSHOT]
	at org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationProvider.authenticate(JwtAuthenticationProvider.java:88) ~[spring-security-oauth2-resource-server-6.0.1.jar!/:6.0.1]
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182) ~[spring-security-core-6.0.1.jar!/:6.0.1]
	at org.springframework.security.authentication.ObservationAuthenticationManager.lambda$authenticate$1(ObservationAuthenticationManager.java:53) ~[spring-security-core-6.0.1.jar!/:6.0.1]
	at io.micrometer.observation.Observation.observe(Observation.java:559) ~[micrometer-observation-1.10.3.jar!/:1.10.3]
	at org.springframework.security.authentication.ObservationAuthenticationManager.authenticate(ObservationAuthenticationManager.java:52) ~[spring-security-core-6.0.1.jar!/:6.0.1]
	at org.springframework.security.oauth2.server.resource.web.authentication.BearerTokenAuthenticationFilter.doFilterInternal(BearerTokenAuthenticationFilter.java:137) ~[spring-security-oauth2-resource-server-6.0.1.jar!/:6.0.1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.4.jar!/:6.0.4]
```

**Comment by rmmayo** [comment]
PR: #2011
