### ISSUE TITLE
Undeclared variable log in H2NativeRepo

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#232]
```
groovy.lang.MissingPropertyException: No such property: log for class: skills.storage.repos.nativeSql.H2NativeRepo
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65) ~[groovy-3.0.5.jar:3.0.5]
	at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.getProperty(GetEffectivePogoPropertySite.java:87) ~[groovy-3.0.5.jar:3.0.5]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:341) ~[groovy-3.0.5.jar:3.0.5]
	at skills.storage.repos.nativeSql.H2NativeRepo.identifyAndAddSubjectLevelAchievements(H2NativeRepo.groovy:614) ~[classes/:na]
	at skills.storage.repos.nativeSql.NativeQueriesRepo$identifyAndAddSubjectLevelAchievements$3.call(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-3.0.5.jar:3.0.5]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-3.0.5.jar:3.0.5]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:157) ~[groovy-3.0.5.jar:3.0.5]
	at skills.services.UserAchievementsAndPointsManagement.insertUserAchievementWhenDecreaseOfOccurrencesCausesUsersToAchieve(UserAchievementsAndPointsManagement.groovy:134) ~[classes/:na]
	at skills.services.UserAchievementsAndPointsManagement$$FastClassBySpringCGLIB$$df3bc2ea.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367) ~[spring-tx-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[spring-tx-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at skills.services.UserAchievementsAndPointsManagement$$EnhancerBySpringCGLIB$$1b053ca6.insertUserAchievementWhenDecreaseOfOccurrencesCausesUsersToAchieve(<generated>) ~[classes/:na]
	at skills.services.UserAchievementsAndPointsManagement$insertUserAchievementWhenDecreaseOfOccurrencesCausesUsersToAchieve$1.call(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-3.0.5.jar:3.0.5]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-3.0.5.jar:3.0.5]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:166) ~[groovy-3.0.5.jar:3.0.5]
	at skills.services.admin.SkillsAdminService.saveSkill(SkillsAdminService.groovy:206) ~[classes/:na]
```

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/233
