### ISSUE TITLE
Sporadic failures in CI when restarting greenmail server

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2364]
```
[INFO] Running ContactOwnersSpec
Error: Exception in thread "smtp:127.0.0.1:3025" java.lang.IllegalStateException: Can not open server socket for smtp:127.0.0.1:3025
	at com.icegreen.greenmail.server.AbstractServer.initServerSocket(AbstractServer.java:123)
	at com.icegreen.greenmail.server.AbstractServer.run(AbstractServer.java:94)
Caused by: java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.Net.bind(Net.java:544)
	at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:629)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:393)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:341)
	at com.icegreen.greenmail.server.AbstractServer.openServerSocket(AbstractServer.java:74)
	at com.icegreen.greenmail.server.AbstractServer.initServerSocket(AbstractServer.java:118)
	... 1 more
```

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/2366
