### ISSUE TITLE
Skills Display: Search across all skills input removes/adds input characters

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#2658]
![image](https://github.com/NationalSecurityAgency/skills-service/assets/51749745/7c61c7aa-1877-4a25-b4ed-306ec29d7a18)

type a search string, then delete and retype some of the chars

there looks to be an error in th dev console: 

```
apexCharts-B0zQDcU8.js:13 TypeError: Assignment to constant variable.
    at O.onUpdate:modelValue.f.<computed>.f.<computed> (skillsDisplay-CCVzWXip.js:62:40703)
    at Ge (apexCharts-B0zQDcU8.js:13:38)
    at ge (apexCharts-B0zQDcU8.js:13:109)
    at cl (apexCharts-B0zQDcU8.js:13:2205)
    at Proxy.updateModel (primevueComponents-D1UmfNDg.js:175:14408)
    at Proxy.onInput (primevueComponents-D1UmfNDg.js:175:4441)
    at Yd.t.multiple.u.onInput.e.<computed>.e.<computed> (primevueComponents-D1UmfNDg.js:175:19846)
    at Ge (apexCharts-B0zQDcU8.js:13:38)
    at ge (apexCharts-B0zQDcU8.js:13:109)
    at HTMLInputElement.x (apexCharts-B0zQDcU8.js:17:7385)
```

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/2661

**Comment by dwalizer** [comment]
:+1:
