### ISSUE TITLE
In certain situations dashboard fails to delete a skill event

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#295]
The following error is emitted in the log: 
```
Jan 27 11:59:16 ip-10-113-80-149 skills-service.cnt94rqtk5o7r5hqt8u2og4d5.qnwqkzi[18465]: java.lang.NullPointerException: Cannot get property 'points' on null object
Jan 27 11:59:16 ip-10-113-80-149 skills-service.cnt94rqtk5o7r5hqt8u2og4d5.qnwqkzi[18465]:       at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60) ~[groovy-3.0.5.jar!/:3.0.5]
Jan 27 11:59:16 ip-10-113-80-149 skills-service.cnt94rqtk5o7r5hqt8u2og4d5.qnwqkzi[18465]:       at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318) ~[groovy-3.0.5.jar!/:3.0.5]
Jan 27 11:59:16 ip-10-113-80-149 skills-service.cnt94rqtk5o7r5hqt8u2og4d5.qnwqkzi[18465]:       at skills.services.SkillEventAdminService.doUpdateUserPoints(SkillEventAdminService.groovy:156) ~[classes!/:1.3.1]
Jan 27 11:59:16 ip-10-113-80-149 skills-service.cnt94rqtk5o7r5hqt8u2og4d5.qnwqkzi[18465]:       at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318) ~[groovy-3.0.5.jar!/:3.0.5]
Jan 27 11:59:16 ip-10-113-80-149 skills-service.cnt94rqtk5o7r5hqt8u2og4d5.qnwqkzi[18465]:       at skills.services.SkillEventAdminService.updateUserPoints(SkillEventAdminService.groovy:149) ~[classes!/:1.3.1]
Jan 27 11:59:16 ip-10-113-80-149 skills-service.cnt94rqtk5o7r5hqt8u2og4d5.qnwqkzi[18465]:       at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318) ~[groovy-3.0.5.jar!/:3.0.5]
Jan 27 11:59:16 ip-10-113-80-149 skills-service.cnt94rqtk5o7r5hqt8u2og4d5.qnwqkzi[18465]:       at skills.services.SkillEventAdminService.updateByTraversingUpSkillDefs(SkillEventAdminService.groovy:179) ~[classes!/:1.3.1]
```

**Comment by sudo-may** [comment]
could not reproduce
