### ISSUE TITLE
POST ``/root/global/settings`` fails if the ``value=null`` when debugging is enabled that causes ``SettingsRequest.toString`` to be called

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#484]
POST ``/root/global/settings`` fails if the ``value=null`` when debugging is enabled that causes ``SettingsRequest.toString`` to be called

```
java.lang.NullPointerException: Cannot invoke method toLowerCase() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91) ~[groovy-3.0.7.jar!/:3.0.7]
	at org.codehaus.groovy.vmplugin.v8.IndyGuardsFiltersAndSignatures.invokeGroovyObjectInvoker(IndyGuardsFiltersAndSignatures.java:160) ~[groovy-3.0.7.jar!/:3.0.7]
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318) ~[groovy-3.0.7.jar!/:3.0.7]
	at skills.controller.request.model.SettingsRequest.isEnabled(SettingsRequest.groovy:31) ~[classes!/:1.4.0-SNAPSHOT]
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318) ~[groovy-3.0.7.jar!/:3.0.7]
	at skills.controller.request.model.SettingsRequest.toString(SettingsRequest.groovy) ~[classes!/:1.4.0-SNAPSHOT]
	at org.codehaus.groovy.runtime.InvokerHelper.format(InvokerHelper.java:677) ~[groovy-3.0.7.jar!/:3.0.7]
	at org.codehaus.groovy.runtime.InvokerHelper.formatCollection(InvokerHelper.java:763) ~[groovy-3.0.7.jar!/:3.0.7]
	at org.codehaus.groovy.runtime.InvokerHelper.format(InvokerHelper.java:652) ~[groovy-3.0.7.jar!/:3.0.7]
	at org.codehaus.groovy.runtime.InvokerHelper.toString(InvokerHelper.java:152) ~[groovy-3.0.7.jar!/:3.0.7]
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:232) ~[groovy-3.0.7.jar!/:3.0.7]
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318) ~[groovy-3.0.7.jar!/:3.0.7]
	at jdk.internal.reflect.GeneratedMethodAccessor510.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644) ~[spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633) ~[spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) ~[spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95) ~[spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at skills.controller.RootController$$EnhancerBySpringCGLIB$$bf4ad94c.saveGlobalSettings(<generated>) ~[classes!/:1.4.0-SNAPSHOT]
```

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/485

**Comment by mosefer** [comment]
:+1:
