### ISSUE TITLE
Possible NPE in ``SubscribedDestinationRegistry``

### ISSUE THREAD

**Issue by rmmayo** [NationalSecurityAgency/skills-service#506]
```
Apr  9 19:09:26 ip-10-113-80-224 skills-service.fx4ld4la5pg4slkk972jzvyxu.ubl7e8w[10033]: 2021-04-09 19:09:26.891 ERROR 9 --- [io-8443-exec-39] o.s.w.s.m.StompSubProtocolHandler        : Error publishing SessionSubscribeEvent[GenericMessa
ge [payload=byte[0], headers={simpMessageType=SUBSCRIBE, stompCommand=SUBSCRIBE, nativeHeaders={id=[sub-1617995366822-720], destination=[/user/queue/movies-skill-updates]}, simpSessionAttributes={}, simpHeartbeat=[J@733bbbaf, simpSubscrip
tionId=sub-1617995366822-720, simpSessionId=4sx1u2b0, simpDestination=/user/queue/movies-skill-updates}]]
Apr  9 19:09:26 ip-10-113-80-224 skills-service.fx4ld4la5pg4slkk972jzvyxu.ubl7e8w[10033]: 
Apr  9 19:09:26 ip-10-113-80-224 skills-service.fx4ld4la5pg4slkk972jzvyxu.ubl7e8w[10033]: java.lang.NullPointerException: null
Apr  9 19:09:26 ip-10-113-80-224 skills-service.fx4ld4la5pg4slkk972jzvyxu.ubl7e8w[10033]:       at skills.websocket.SubscribedDestinationRegistry.onApplicationEvent(SubscribedDestinationRegistry.groovy:93) ~[classes!/:1.4.0-SNAPSHOT]
Apr  9 19:09:26 ip-10-113-80-224 skills-service.fx4ld4la5pg4slkk972jzvyxu.ubl7e8w[10033]:       at skills.websocket.SubscribedDestinationRegistry.onApplicationEvent(SubscribedDestinationRegistry.groovy) ~[classes!/:1.4.0-SNAPSHOT]
Apr  9 19:09:26 ip-10-113-80-224 skills-service.fx4ld4la5pg4slkk972jzvyxu.ubl7e8w[10033]:       at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-c
ontext-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
Apr  9 19:09:26 ip-10-113-80-224 skills-service.fx4ld4la5pg4slkk972jzvyxu.ubl7e8w[10033]:       at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-con
text-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
Apr  9 19:09:26 ip-10-113-80-224 skills-service.fx4ld4la5pg4slkk972jzvyxu.ubl7e8w[10033]:       at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-con
text-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
Apr  9 19:09:26 ip-10-113-80-224 skills-service.fx4ld4la5pg4slkk972jzvyxu.ubl7e8w[10033]:       at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404) ~[spring-context-5.2.8.REL
EASE.jar!/:5.2.8.RELEASE]
Apr  9 19:09:26 ip-10-113-80-224 skills-service.fx4ld4la5pg4slkk972jzvyxu.ubl7e8w[10033]:       at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361) ~[spring-context-5.2.8.REL
EASE.jar!/:5.2.8.RELEASE]
Apr  9 19:09:26 ip-10-113-80-224 skills-service.fx4ld4la5pg4slkk972jzvyxu.ubl7e8w[10033]:       at org.springframework.web.socket.messaging.StompSubProtocolHandler.publishEvent(StompSubProtocolHandler.java:403) ~[spring-websocket-5.2.8.RE
LEASE.jar!/:5.2.8.RELEASE]
Apr  9 19:09:26 ip-10-113-80-224 skills-service.fx4ld4la5pg4slkk972jzvyxu.ubl7e8w[10033]:       at org.springframework.web.socket.messaging.StompSubProtocolHandler.handleMessageFromClient(StompSubProtocolHandler.java:315) ~[spring-websock
et-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
Apr  9 19:09:26 ip-10-113-80-224 skills-service.fx4ld4la5pg4slkk972jzvyxu.ubl7e8w[10033]:       at org.springframework.web.socket.messaging.SubProtocolWebSocketHandler.handleMessage(SubProtocolWebSocketHandler.java:335) ~[spring-websocket
-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
Apr  9 19:09:26 ip-10-113-80-224 skills-service.fx4ld4la5pg4slkk972jzvyxu.ubl7e8w[10033]:       at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleMessage(WebSocketHandlerDecorator.java:75) ~[spring-websocket-5.2.8.
RELEASE.jar!/:5.2.8.RELEASE]
Apr  9 19:09:26 ip-10-113-80-224 skills-service.fx4ld4la5pg4slkk972jzvyxu.ubl7e8w[10033]:       at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleMessage(LoggingWebSocketHandlerDecorator.java:56) ~[spring-we
bsocket-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
Apr  9 19:09:26 ip-10-113-80-224 skills-service.fx4ld4la5pg4slkk972jzvyxu.ubl7e8w[10033]:       at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.handleMessage(ExceptionWebSocketHandlerDecorator.java:58) ~[sprin
g-websocket-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
Apr  9 19:09:26 ip-10-113-80-224 skills-service.fx4ld4la5pg4slkk972jzvyxu.ubl7e8w[10033]:       at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.delegateMessages(AbstractSockJsSession.java:387) ~[spring-web
socket-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
Apr  9 19:09:26 ip-10-113-80-224 skills-service.fx4ld4la5pg4slkk972jzvyxu.ubl7e8w[10033]:       at org.springframework.web.socket.sockjs.transport.handler.AbstractHttpReceivingTransportHandler.handleRequestInternal(AbstractHttpReceivingTr
ansportHandler.java:90) ~[spring-websocket-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
Apr  9 19:09:26 ip-10-113-80-224 skills-service.fx4ld4la5pg4slkk972jzvyxu.ubl7e8w[10033]:       at org.springframework.web.socket.sockjs.transport.handler.AbstractHttpReceivingTransportHandler.handleRequest(AbstractHttpReceivingTransportH
andler.java:54) ~[spring-websocket-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
Apr  9 19:09:26 ip-10-113-80-224 skills-service.fx4ld4la5pg4slkk972jzvyxu.ubl7e8w[10033]:       at org.springframework.web.socket.sockjs.transport.TransportHandlingSockJsService.handleTransportRequest(TransportHandlingSockJsService.java:3
13) ~[spring-websocket-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
Apr  9 19:09:26 ip-10-113-80-224 skills-service.fx4ld4la5pg4slkk972jzvyxu.ubl7e8w[10033]:       at org.springframework.web.socket.sockjs.support.AbstractSockJsService.handleRequest(AbstractSockJsService.java:439) ~[spring-websocket-5.2.8.
RELEASE.jar!/:5.2.8.RELEASE]
Apr  9 19:09:26 ip-10-113-80-224 skills-service.fx4ld4la5pg4slkk972jzvyxu.ubl7e8w[10033]:       at org.springframework.web.socket.sockjs.support.SockJsHttpRequestHandler.handleRequest(SockJsHttpRequestHandler.java:134) ~[spring-websocket-
5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
Apr  9 19:09:26 ip-10-113-80-224 skills-service.fx4ld4la5pg4slkk972jzvyxu.ubl7e8w[10033]:       at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:53) ~[spring-webmvc-5.2.8.RELEASE.jar!/
:5.2.8.RELEASE]
Apr  9 19:09:26 ip-10-113-80-224 skills-service.fx4ld4la5pg4slkk972jzvyxu.ubl7e8w[10033]:       at org.spr
```

**Comment by rmmayo** [comment]
PR: #507
