### ISSUE TITLE
Unable to notify pending achievements error

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#69]
noticed the following exception in ``skills-service`` logs:

```
skills-service.0.mxullhq482ni@ip-10-113-80-36.evoforge.org    | 2020-08-31 18:39:19.733 ERROR 8 --- [cTaskExecutor-2] s.services.events.SkillEventsService     : unable to notify user [000000000002] of pending achievements
skills-service.0.mxullhq482ni@ip-10-113-80-36.evoforge.org    | 
skills-service.0.mxullhq482ni@ip-10-113-80-36.evoforge.org    | java.lang.IllegalArgumentException: Parameter projectId in SkillEventsSupportRepo.findByProjectIdAndSkillId must not be null!
skills-service.0.mxullhq482ni@ip-10-113-80-36.evoforge.org    | 	at org.springframework.data.repository.core.support.MethodInvocationValidator.invoke(MethodInvocationValidator.java:94) ~[spring-data-commons-2.1.16.RELEASE.jar!/:2.1.16.RELEASE]
skills-service.0.mxullhq482ni@ip-10-113-80-36.evoforge.org    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
skills-service.0.mxullhq482ni@ip-10-113-80-36.evoforge.org    | 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
skills-service.0.mxullhq482ni@ip-10-113-80-36.evoforge.org    | 	at com.sun.proxy.$Proxy196.findByProjectIdAndSkillId(Unknown Source) ~[na:na]
skills-service.0.mxullhq482ni@ip-10-113-80-36.evoforge.org    | 	at skills.services.events.SkillEventsService$_notifyUserOfAchievements_closure1.doCall(SkillEventsService.groovy:99) ~[classes!/:1.2.0-SNAPSHOT]
skills-service.0.mxullhq482ni@ip-10-113-80-36.evoforge.org    | 	at skills.services.events.SkillEventsService$_notifyUserOfAchievements_closure1.call(SkillEventsService.groovy) ~[classes!/:1.2.0-SNAPSHOT]
skills-service.0.mxullhq482ni@ip-10-113-80-36.evoforge.org    | 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2330) ~[groovy-2.5.9.jar!/:2.5.9]
skills-service.0.mxullhq482ni@ip-10-113-80-36.evoforge.org    | 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2315) ~[groovy-2.5.9.jar!/:2.5.9]
skills-service.0.mxullhq482ni@ip-10-113-80-36.evoforge.org    | 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2356) ~[groovy-2.5.9.jar!/:2.5.9]
skills-service.0.mxullhq482ni@ip-10-113-80-36.evoforge.org    | 	at skills.services.events.SkillEventsService.notifyUserOfAchievements(SkillEventsService.groovy:98) ~[classes!/:1.2.0-SNAPSHOT]
skills-service.0.mxullhq482ni@ip-10-113-80-36.evoforge.org    | 	at skills.services.events.SkillEventsService.identifyPendingNotifications(SkillEventsService.groovy:146) ~[classes!/:1.2.0-SNAPSHOT]
skills-service.0.mxullhq482ni@ip-10-113-80-36.evoforge.org    | 	at skills.services.events.SkillEventsService$$FastClassBySpringCGLIB$$51008f3c.invoke(<generated>) ~[classes!/:1.2.0-SNAPSHOT]
skills-service.0.mxullhq482ni@ip-10-113-80-36.evoforge.org    | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
skills-service.0.mxullhq482ni@ip-10-113-80-36.evoforge.org    | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:750) ~[spring-aop-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
skills-service.0.mxullhq482ni@ip-10-113-80-36.evoforge.org    | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
skills-service.0.mxullhq482ni@ip-10-113-80-36.evoforge.org    | 	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.1.14.RELEASE.jar!/:5.1.14.RELEASE]
skills-service.0.mxullhq482ni@ip-10-113-80-36.evoforge.org    | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
skills-service.0.mxullhq482ni@ip-10-113-80-36.evoforge.org    | 	at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
skills-service.0.mxullhq482ni@ip-10-113-80-36.evoforge.org    | 
```

**Comment by rmmayo** [comment]
@mosefer - tried testing but I did not receive any notification.  I may just not be testing it correctly?

 Here's what I did:

1. logged into dashboard as an admin of movies project
1. created a new skill under the "Action" subject called test.
    - two occurences, 50 points each, no time window
    ![image](https://user-images.githubusercontent.com/47030042/93385036-a09ebe80-f833-11ea-9e7f-c0328680565e.png)
1. Went to "Manage" for that skill, "Add Event" and added two events for "user1" to achieve the skill
    ![image](https://user-images.githubusercontent.com/47030042/93385242-f96e5700-f833-11ea-9d13-27c77b558870.png)
1. Created  a global badge, added that skill, and the clicked "Go Live"
    ![image](https://user-images.githubusercontent.com/47030042/93385699-9af5a880-f834-11ea-893f-100db4d1e7e6.png)
    ![image](https://user-images.githubusercontent.com/47030042/93385608-7a2d5300-f834-11ea-83f3-351131fbe719.png)
1. Opened the [user-examples app](https://ip-10-113-80-245.evoforge.org:8090/vuejs#/showSkills?refreshPage=true) which show the client display for user1 and expected to be notified that I achieved the global badge but was not  :cry:

**Comment by rmmayo** [comment]
Tested again today with @mosefer and both of use received global badge notifications.  

```
{
  "success": true,
  "projectId": null,
  "skillId": "testBadge",
  "name": "test",
  "pointsEarned": 0,
  "skillApplied": true,
  "explanation": "Achieved due to a modification in the training profile (such as: skill deleted, occurrences modified, badge published, etc..)",
  "completed": [
    {
      "type": "GlobalBadge",
      "level": null,
      "id": "testBadge",
      "name": "test"
    }
  ]
}
```

I was expected a "toast" style pop-up similar to how the dashboard shows ws notifications, but the examples app displays the actual json content in the "Global Event Result"  section so I must have missed that previously.
