### ISSUE TITLE
``SkillEventsService#notifyUserOfAchievements`` does not consider project level achievements

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#896]
The logic in ``SkillEventsService#notifyUserOfAchievements`` always expects ``skillId`` to exist but ``UserAchievement`` records for project level achievements have ``skillId=null``

```
s.services.events.SkillEventsService : unable to notify user [000000000003] of pending achievements
java.lang.IllegalArgumentException: Parameter skillId in SkillEventsSupportRepo.findByProjectIdAndSkillId must not be null!
at org.springframework.data.repository.core.support.MethodInvocationValidator.invoke(MethodInvocationValidator.java:94) ~[spring-data-commons-2.3.9.RELEASE.jar!/:2.3.9.RELEASE]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
at jdk.proxy2/jdk.proxy2.$Proxy220.findByProjectIdAndSkillId(Unknown Source) ~[na:na]
at skills.services.events.SkillEventsService$_notifyUserOfAchievements_closure1.doCall(SkillEventsService.groovy:127) ~[classes!/:1.7.1-SNAPSHOT]
at skills.services.events.SkillEventsService$_notifyUserOfAchievements_closure1.call(SkillEventsService.groovy) ~[classes!/:1.7.1-SNAPSHOT]
at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2318) ~[groovy-3.0.7.jar!/:3.0.7]
at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2303) ~[groovy-3.0.7.jar!/:3.0.7]
at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2344) ~[groovy-3.0.7.jar!/:3.0.7]
at skills.services.events.SkillEventsService.notifyUserOfAchievements(SkillEventsService.groovy:123) ~[classes!/:1.7.1-SNAPSHOT]
at skills.services.events.SkillEventsService.identifyPendingNotifications(SkillEventsService.groovy:177) ~[classes!/:1.7.1-SNAPSHOT]
at skills.services.events.SkillEventsService$$FastClassBySpringCGLIB$$51008f3c.invoke(<generated>) ~[classes!/:1.7.1-SNAPSHOT]
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[spring-aop-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
at java.base/java.lang.Thread.run(Thread.java:831) ~[na:na]
```

**Comment by mosefer** [comment]
PR: #939

**Comment by sudo-may** [comment]
:+1:
