### ISSUE TITLE
Notify User Achievements throws a NullPointerException

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-service#971]
```
java.lang.NullPointerException: Cannot invoke "skills.storage.repos.SkillEventsSupportRepo$SkillDefMin.getName()" because "skill" is null
at skills.services.events.SkillEventsService$_notifyUserOfAchievements_closure1.doCall(SkillEventsService.groovy:140) ~[classes!/:1.8.0-SNAPSHOT]
at skills.services.events.SkillEventsService$_notifyUserOfAchievements_closure1.call(SkillEventsService.groovy) ~[classes!/:1.8.0-SNAPSHOT]
at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2318) ~[groovy-3.0.7.jar!/:3.0.7]
at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2303) ~[groovy-3.0.7.jar!/:3.0.7]
at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2344) ~[groovy-3.0.7.jar!/:3.0.7]
at skills.services.events.SkillEventsService.notifyUserOfAchievements(SkillEventsService.groovy:130) ~[classes!/:1.8.0-SNAPSHOT]
at skills.services.events.SkillEventsService.identifyPendingNotifications(SkillEventsService.groovy:182) ~[classes!/:1.8.0-SNAPSHOT]
at skills.services.events.SkillEventsService$$FastClassBySpringCGLIB$$51008f3c.invoke(<generated>) ~[classes!/:1.8.0-SNAPSHOT]
```

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-service/pull/975

**Comment by sudo-may** [comment]
:+1:
